"""add user_id to measurements and foods

Revision ID: 37dfa83fa258
Revises: cb1abb7a38a7
Create Date: 2026-06-01 19:26:24.064019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37dfa83fa258'
down_revision: Union[str, Sequence[str], None] = 'cb1abb7a38a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Pre-auth rows cannot be assigned to a Clerk user.
    op.execute("DELETE FROM food_entries")
    op.execute("DELETE FROM body_measurements")

    op.add_column('body_measurements', sa.Column('user_id', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_body_measurements_user_id'), 'body_measurements', ['user_id'], unique=False)
    op.add_column('food_entries', sa.Column('user_id', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_food_entries_user_id'), 'food_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_entries_user_id'), table_name='food_entries')
    op.drop_column('food_entries', 'user_id')
    op.drop_index(op.f('ix_body_measurements_user_id'), table_name='body_measurements')
    op.drop_column('body_measurements', 'user_id')
    # ### end Alembic commands ###
