"""add metabolic profiles

Revision ID: 400b39ab0d58
Revises: 37dfa83fa258
Create Date: 2026-06-01 19:40:56.498952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '400b39ab0d58'
down_revision: Union[str, Sequence[str], None] = '37dfa83fa258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metabolic_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('sex', sa.String(length=16), nullable=False),
    sa.Column('age_years', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('activity_level', sa.String(length=32), nullable=False),
    sa.Column('bmr_kcal', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('tdee_kcal', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metabolic_profiles_user_id'), 'metabolic_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metabolic_profiles_user_id'), table_name='metabolic_profiles')
    op.drop_table('metabolic_profiles')
    # ### end Alembic commands ###
