"""add body measurements

Revision ID: ab2ecb99d416
Revises: af20bfb0a00e
Create Date: 2026-06-01 08:11:38.400601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2ecb99d416'
down_revision: Union[str, Sequence[str], None] = 'af20bfb0a00e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('body_weight_lbs', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('waist_inches', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_measurements_recorded_at'), 'body_measurements', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_body_measurements_recorded_at'), table_name='body_measurements')
    op.drop_table('body_measurements')
    # ### end Alembic commands ###
