"""add food entries

Revision ID: cb1abb7a38a7
Revises: ab2ecb99d416
Create Date: 2026-06-01 19:00:02.191549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1abb7a38a7'
down_revision: Union[str, Sequence[str], None] = 'ab2ecb99d416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('calories', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('estimation_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_entries_recorded_at'), 'food_entries', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_entries_recorded_at'), table_name='food_entries')
    op.drop_table('food_entries')
    # ### end Alembic commands ###
